interface=fakeAp1-wlan0
driver=nl80211
ssid=testnetwork
hw_mode=g
channel=6
wpa=2
wpa_passphrase=abcdefgh
wpa_key_mgmt=FT-PSK WPA-PSK
rsn_pairwise=CCMP

mobility_domain=4f57
ft_over_ds=1

nas_identifier=fakeAp1
